name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    name: Build APK for Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t buildozer-android .

    # Step 3: Run Buildozer in Docker
    - name: Run Buildozer in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -e BUILD_PATH=/app/.buildozer \
          -u 1000:1000 \
          buildozer-android

    # Step 4: Upload APK Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: bin/*.apk
