name: Build APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-android:
    name: Build APK for Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Adjust Permissions (to avoid permission issues)
    - name: Adjust Permissions
      run: chmod -R 777 ${{ github.workspace }}

    # Step 3: Install Android SDK dependencies
    - name: Install Android SDK dependencies
      run: |
        echo "Installing required Android SDK tools..."
        yes | sdkmanager --licenses
        sdkmanager --update
        sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "cmdline-tools;latest"

    # Step 4: Build Docker Image
    - name: Build Docker Image
      run: docker build -t buildozer-android .

    # Step 5: Run Buildozer in Docker
    - name: Run Buildozer in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -e BUILD_PATH=/app/.buildozer \
          -u 1000:1000 \
          buildozer-android

    # Step 6: Upload APK Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: /app/bin/*.apk
