name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build Docker image
      run: docker build -t jedie/buildozer .

    - name: List installed packages
      run: docker run jedie/buildozer pip freeze

    - name: Print version info
      run: |
        docker run jedie/buildozer uname -a
        docker run jedie/buildozer cython --version
        docker run jedie/buildozer buildozer --version

    - name: Echo OK
      run: echo "OK"

    - name: Push Docker image
      if: github.ref == 'refs/heads/master'
      run: docker push jedie/buildozer