name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update System
      run: sudo apt update

    - name: Install Required Packages
      run: |
        sudo apt install -y git zip unzip openjdk-17-jdk python3.9 python3.9-venv python3.9-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Upgrade pip for Python 3.9
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py

    - name: Install Python Packages Globally
      run: |
        sudo pip3.9 install --upgrade Cython==0.29.33 pyjnius virtualenv buildozer

    - name: Add Local Binary Path to Environment
      run: |
        echo 'export PATH=$PATH:~/.local/bin/' >> ~/.bashrc
        source ~/.bashrc

    - name: Clone Repository
      run: |
        git clone https://github.com/DvidMakesThings/FlashCards.git ~/FlashCards

    - name: Build APK
      run: |
        cd ~/FlashCards
        yes | buildozer -v android debug

    - name: Upload APK to Repository
      env:
        PUSH: ${{ secrets.PUSH }}
      run: |
        cd ~/FlashCards
        mkdir -p bin
        mv bin/*.apk ./bin/
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "APK autobuilder [skip ci]"
        git push https://DvidMakesThings:${PUSH}@github.com/DvidMakesThings/FlashCards.git master
