name: Build APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-android:
    name: Build APK for Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Adjust Permissions (to avoid permission issues)
    - name: Adjust Permissions
      run: chmod -R 777 ${{ github.workspace }}

    # Step 3: Install Android SDK Command-Line Tools
    - name: Install Android SDK Command-Line Tools
      run: |
        echo "Installing Android SDK Command-Line Tools..."
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/Android/cmdline-tools
        unzip -q cmdline-tools.zip -d $HOME/Android/cmdline-tools
        mv $HOME/Android/cmdline-tools/cmdline-tools $HOME/Android/cmdline-tools/latest
        rm cmdline-tools.zip
        export ANDROID_HOME=$HOME/Android
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
        
        # Accept licenses automatically
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

        # Install necessary SDK components (including build tools and platforms)
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33" "cmdline-tools;latest"

    # Step 4: Install AIDL
    - name: Install AIDL
      run: |
        echo "Installing AIDL..."
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.0" "platforms;android-33" "cmdline-tools;latest" "aidl"

    # Step 5: Build Docker Image
    - name: Build Docker Image
      run: docker build -t buildozer-android .

    # Step 6: Run Buildozer in Docker
    - name: Run Buildozer in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          -e BUILD_PATH=/app/.buildozer \
          -u 1000:1000 \
          buildozer-android

    # Step 7: Upload APK Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: APK
        path: /app/bin/*.apk
