name: Build APK
on:
 push:
   branches:
     - master
jobs:
 build-apk:
   runs-on: ubuntu-20.04
   steps:
   - name: Checkout Repository
     uses: actions/checkout@v3
   - name: Update System
     run: sudo apt update
   - name: Install Required Packages
     run: |
       sudo apt install -y git zip unzip openjdk-17-jdk python3.9 python3.9-venv python3.9-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
   - name: Set Java 17 as Default
     run: |
       sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
       sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
       sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac 1
       sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
       export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
   - name: Verify Java Version
     run: |
       java -version
       echo $JAVA_HOME
   - name: Create Virtual Environment
     run: |
       python3.9 -m venv ~/venv
       source ~/venv/bin/activate
       python -m pip install --upgrade pip
   - name: Install Python Packages in venv
     run: |
       source ~/venv/bin/activate
       pip install --upgrade Cython==0.29.33 pyjnius virtualenv buildozer
   - name: Clone FlashCards Repository
     run: git clone https://github.com/DvidMakesThings/FlashCards.git ~/FlashCards
   - name: Force Cythonize pyjnius Manually
     run: |
       source ~/venv/bin/activate
       git clone https://github.com/kivy/pyjnius.git ~/pyjnius
       cd ~/pyjnius
       python setup.py build_ext --inplace
       pip install .
   - name: Build APK
     run: |
       source ~/venv/bin/activate
       cd ~/FlashCards
       yes | buildozer -v android debug
   - name: Upload APK to Repository
     env:
       PUSH: ${{ secrets.PUSH }}
     run: |
       cd ~/FlashCards
       mkdir -p bin
       mv bin/*.apk ./bin/ || echo "No APK found to upload"
       git config --global user.name "github-actions[bot]"
       git config --global user.email "github-actions[bot]@users.noreply.github.com"
       git add .
       git commit -m "APK autobuilder [skip ci]"
       git push https://DvidMakesThings:${PUSH}@github.com/DvidMakesThings/FlashCards.git master