name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Buildozer
      run: |
        sudo apt update
        sudo apt install -y python3-pip
        pip install buildozer

    - name: Install Android SDK and NDK
      run: |
        sudo apt install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android/cmdline-tools
        unzip cmdline-tools.zip -d $HOME/android/cmdline-tools
        mv $HOME/android/cmdline-tools/cmdline-tools $HOME/android/cmdline-tools/tools
        rm cmdline-tools.zip
        yes | $HOME/android/cmdline-tools/tools/bin/sdkmanager --sdk_root=$HOME/android 'platform-tools' 'build-tools;33.0.0' 'platforms;android-33'

    - name: Build APK
      run: |
        buildozer android debug
