name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update System
      run: sudo apt update

    - name: Install Required Packages
      run: |
        sudo apt install -y git zip unzip openjdk-17-jdk python3.9 python3.9-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Upgrade pip for Python 3.9
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py

    - name: Install Python Packages
      run: |
        pip3.9 install --upgrade Cython==0.29.33 virtualenv buildozer

    - name: Install Android SDK Command-Line Tools
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        rm cmdline-tools.zip

    - name: Install Required Android Components
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --install "build-tools;31.0.0" "platform-tools" "platforms;android-30"
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      run: |
        git clone https://github.com/DvidMakesThings/FlashCards.git ~/FlashCards
        cd ~/FlashCards
        export ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        export ANDROID_NDK_HOME=$HOME/.buildozer/android/platform/android-ndk-r25b
        export ANDROID_HOME=$ANDROID_SDK_ROOT
        buildozer -v android debug

    - name: Upload APK to Repository
      run: |
        cd ~/FlashCards
        mkdir -p bin
        mv bin/*.apk ./bin/
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./bin/
        git commit -m "Upload APK [skip ci]"
        git push
