name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update System
      run: |
        sudo apt update

    - name: Install Required Packages
      run: |
        sudo apt install -y git zip unzip openjdk-17-jdk python3.9 python3.9-dev autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

    - name: Upgrade pip for Python 3.9
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py

    - name: Install Python Packages
      run: |
        pip3.9 install --upgrade Cython==0.29.33 virtualenv buildozer

    - name: Install Android SDK and Accept Licenses
      run: |
        mkdir -p ~/.android
        echo '24333f8a63b6825ea9c5514f83c2829b004d1fee' > ~/.android/repositories.cfg || true
        $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --install "build-tools;36.0.0-rc1" --verbose || true
        yes | $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --licenses || true

    - name: Build APK
      run: |
        git clone https://github.com/DvidMakesThings/FlashCards.git ~/FlashCards
        cd ~/FlashCards
        buildozer -v android debug

    - name: Upload APK to Repository
      run: |
        cd ~/FlashCards
        mkdir -p bin
        mv bin/*.apk ./bin/
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./bin/
        git commit -m "Upload APK [skip ci]"
        git push
