name: Build and Push APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t buildozer-android .

      - name: Run Docker container to build APK
        run: docker run --name buildozer-container -v ${PWD}:/home/builder/source buildozer-android

      - name: List contents of source directory
        run: docker exec buildozer-container ls -R /home/builder/source

      - name: Move APK to bin folder
        run: |
          mkdir -p bin
          docker cp buildozer-container:/home/builder/source/.buildozer/android/platform/build-arm64-v8a/dists/your_project_name/bin/*.apk bin/
        shell: bash

      - name: Commit and push APK to bin folder
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add bin/*.apk
          git commit -m "Add built APK"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: docker rm -f buildozer-container