name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update System and Install Required Packages
      run: | 
        sudo apt update
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py
        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3.9 \
          python3.9-venv \
          python3.9-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Create and activate virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        sudo pip3.9 install --upgrade Cython==0.29.33 pyjnius virtualenv buildozer
        sudo python3.9 -m pip install --force-reinstall Cython==0.29.33
        export PATH=$PATH:~/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
        export PYTHONPATH=$HOME/.local/lib/python3.9/site-packages:/usr/local/lib/python3.9/dist-packages:$PYTHONPATH

    - name: Clone FlashCards Repository
      run: git clone https://github.com/DvidMakesThings/FlashCards.git ~/FlashCards

    - name: Verify Python Packages Installation
      run: |
        python3.9 -m pip show Cython
        python3.9 -m pip show pyjnius
        python3.9 -m pip show virtualenv
        python3.9 -m pip show buildozer

    - name: Build APK
      run: |
        cd ~/FlashCards
        yes | buildozer -v android debug

    - name: Upload APK to Repository
      env:
        PUSH: ${{ secrets.PUSH }}
      run: |
        cd ~/FlashCards
        mkdir -p bin
        mv bin/*.apk ./bin/ || echo "No APK found to upload"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "APK autobuilder [skip ci]"
        git push https://DvidMakesThings:${PUSH}@github.com/DvidMakesThings/FlashCards.git master
