name: Build APK

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-android:
    name: Build APK for Android
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Build Docker Image
      run: |
        docker build -t buildozer-android .

    # Step 3: Run the Docker Container
    - name: Run Buildozer in Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/app -u $(id -u):$(id -g) buildozer-android

    # Step 4: Upload APK Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: bin/*.apk
