name: Build APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update System and Install Required Packages
      run: | 
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install -y \
          python3.9 \
          python3.9-venv \
          python3.9-dev \
        pip3 install --user --upgrade buildozer
        python3.9 -m venv venv
        source venv/bin/activate
        sudo apt install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py

    - name: Install Required Python Packages
      run: |
        pip install --upgrade pip
        pip3 install --upgrade Cython==0.29.33 virtualenv
        pip install --force-reinstall Cython==0.29.33

    - name: Clone FlashCards Repository
      run: git clone https://github.com/DvidMakesThings/FlashCards.git ~/FlashCards

    - name: Build APK
      run: |
        cd ~/FlashCards
        yes | buildozer -v android debug

    - name: Upload APK to Repository
      env:
        PUSH: ${{ secrets.PUSH }}
      run: |
        cd ~/FlashCards
        mkdir -p bin
        mv bin/*.apk ./bin/ || echo "No APK found to upload"
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "APK autobuilder [skip ci]"
        git push https://DvidMakesThings:${{ secrets.PUSH }}@github.com/DvidMakesThings/FlashCards.git master